### ISSUE TITLE
很喜欢本主题，便移植到了Ghost

### ISSUE THREAD

**Issue by uvexz** [hi-caicai/farbox-theme-Mind#2]
请问可以吗， 不可以的话我就把它清空

https://github.com/ygbhf/anatole-ghost-theme

**Comment by hi-caicai** [comment]
好棒！有预览效果么？

------------------ Original ------------------

**Comment by uvexz** [comment]
这里： https://blog-yoursever.rhcloud.com/

**Comment by hi-caicai** [comment]
很酷哎，这样其实就够了，不过文章内页，左侧不希望 进行图片加载，如果加载需要做另一种样式比较好看

------------------ Original ------------------

**Comment by uvexz** [comment]
我试试改一改

**Comment by hi-caicai** [comment]
如果有需求，欢迎提，哈哈，我可以对应ghost 进行优化设计
